include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - prefer_single_quotes
    - unawaited_futures
    - sort_child_properties_last
    - directives_ordering

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    unused_import: warning
    invalid_assignment: warning
    missing_return: error 