name: shake
description: A flutter package to detect phone shakes. Adjustable G-force and reset periods.
version: 2.3.0
homepage: https://www.github.com/deven98/shake

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
